=== medinirupam28/storeverse/products.dtd
<!ELEMENT products (product+)>

<!ELEMENT product (name, category, shop, price)>

<!ATTLIST product id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT shop (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== medinirupam28/storeverse/products.xml
<?xml version="1.0"?>

<!DOCTYPE products SYSTEM "products.dtd">

<products>

    <product id="P101">
        <name>Laptop</name>
        <category>Electronics</category>
        <shop>TechHub</shop>
        <price>50000</price>
    </product>

    <product id="P102">
        <name>T-Shirt</name>
        <category>Fashion</category>
        <shop>StyleHub</shop>
        <price>999</price>
    </product>

    <product id="P103">
        <name>Grocery Pack</name>
        <category>Grocery</category>
        <shop>FreshMart</shop>
        <price>499</price>
    </product>

</products>
